### ISSUE TITLE
x axis scrollbar?

### ISSUE THREAD

**Issue by Ksengine** [linuxlawson/texpert#10]
**no x axis scrollbar?**

same window, one line
![Screenshot_2020-11-21_09-32-08](https://user-images.githubusercontent.com/63494497/99874074-abcbed00-2bdc-11eb-9439-6fb1dc54a992.png)
![Screenshot_2020-11-21_09-31-45](https://user-images.githubusercontent.com/63494497/99874075-ae2e4700-2bdc-11eb-87be-9aebdf0b5bd4.png)

**Comment by linuxlawson** [comment]
Is that print preview window? Try it now, should be fixed.

**Comment by Ksengine** [comment]
> Is that print preview window? Try it now, should be fixed.

no
fix it

**Comment by linuxlawson** [comment]
I don't know whats happening there. I'm not having that problem.
