### ISSUE TITLE
notes pane covers text box

### ISSUE THREAD

**Issue by Ksengine** [linuxlawson/texpert#11]
![Screenshot_2020-11-21_09-36-50](https://user-images.githubusercontent.com/63494497/99874149-57753d00-2bdd-11eb-9d44-0b8772a9dbcf.png)
![Screenshot_2020-11-21_09-37-14](https://user-images.githubusercontent.com/63494497/99874150-58a66a00-2bdd-11eb-8445-ebf9c06f21db.png)

**Comment by linuxlawson** [comment]
I know that's like that. I didn't plan on fixing it..

**Comment by Ksengine** [comment]
> I know that's like that. I didn't plan on fixing it..

bad

**Comment by linuxlawson** [comment]
The notes button is a toggle switch, if notes are in the way just close it.

**Comment by Ksengine** [comment]
When notes expanded, we should lower the with of text box

**Comment by linuxlawson** [comment]
Sorry, didn't mean to close this without commenting, was a mistake. 
I thought about doing something with the margins there before but never got around to it.

**Comment by Ksengine** [comment]
Dont close issues if they aren't fixed
