### ISSUE TITLE
save

### ISSUE THREAD

**Issue by Ksengine** [linuxlawson/texpert#12]
> File menu (save)
In the file menu, "save as" works fine. But cannot get "save" to work with one click. 
Would like it to automatically overwrite file/document without opening up dialog box. 
Have tried and failed miserably. I think maybe has something to do with how file opens?
Right now, all save and save as buttons are connected to save as.

can i make a pr

**Comment by linuxlawson** [comment]
Pull request? what happens after that?

**Comment by Ksengine** [comment]
Pull requests are in https://github.com/linuxlawson/texpert/pulls
I had made a pr to fix save method (you defined on todo list)
Accept my pr and merge it

**Comment by linuxlawson** [comment]
Hold on, I seem to have broke something. Im trying to get it back to normal, then I will merge.

**Comment by Ksengine** [comment]
i will do it

**Comment by linuxlawson** [comment]
How do I accept pull request and merge?

**Comment by linuxlawson** [comment]
Thanks for fixing the save function, appreciate it! 👍🏻
