### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by Ksengine** [linuxlawson/texpert#16]
I like to develop this repo
**report any bugs, Ideas or questions as issues**
I will help you

**Comment by Ksengine** [comment]
any future contributors can comment to this issue
**any contributors are welcomed :exclamation::exclamation::exclamation:**

**Comment by Ksengine** [comment]
pin this issue

**Comment by Ksengine** [comment]
report text printing feature as issue

**Comment by linuxlawson** [comment]
print is disabled, I never configured that because I don't have a printer.

**Comment by Ksengine** [comment]
> print is disabled, I never configured that because I don't have a printer.

use https://github.com/shantanubhadoria/python-printer-escpos

**Comment by Ksengine** [comment]
or https://smallbusiness.chron.com/sending-things-printer-python-58655.html

**Comment by Ksengine** [comment]
why closed?

**Comment by linuxlawson** [comment]
I dont need anymore?

**Comment by Ksengine** [comment]
Accept my invitation @quantumgui
