### ISSUE TITLE
overwrite feature

### ISSUE THREAD

**Issue by Ksengine** [linuxlawson/texpert#17]
> Would like to include overwrite feature to edit menu, 
but dont know if that can be done using tkinter, cant find any info, anywhere. 

Can you explain more?

**Comment by linuxlawson** [comment]
The overwrite feature allows you to fix errors in text simply by typing over the existing text. Characters get erased as you type over them. Its a quick way to fix typing errors (once you get used to it). Most text editors have this feature, it is usually enabled with the 'insert' key. Overwrite usually turns your cursor into a block-cursor. 

I'm sure there is an editor on your computer with this feature, try and see.

**Comment by linuxlawson** [comment]
Tkinter has a block-cursor option, but I could not find any info on overwrite, It may not be able to be done with Tkinter.

**Comment by Ksengine** [comment]
You means `insert` key like feature.
Am I correct

**Comment by linuxlawson** [comment]
Yes correct.

**Comment by linuxlawson** [comment]
I tried different combinations of insert method, like below, but could not make it work.  

`texpert.config(padx=2, pady=0, wrap="word", blockcursor=True)  
  
texpert.insert('insert', '')
texpert.insert('insert +1c', '')`

**Comment by linuxlawson** [comment]
overwrite does like this...
![owrite](https://user-images.githubusercontent.com/39196767/101979447-28297d00-3c2b-11eb-807b-d12256952751.gif)

**Comment by Ksengine** [comment]
Set `widget.focus_set()`
Then `widget.event_generate("<Insert>")`
Try it. I cant make a pr now.

**Comment by linuxlawson** [comment]
That is not working, it is pushing text over, not writing over.

**Comment by Ksengine** [comment]
> That is not working, it is pushing text over, not writing over.

If you really pressed insert key, is it works?

**Comment by linuxlawson** [comment]
I tried it again, not working.

**Comment by Ksengine** [comment]
I means
If you manually triggered insert key?

**Comment by linuxlawson** [comment]
Yes I tried pressing the insert key, nothing happened.

**Comment by Ksengine** [comment]
It means we should invent the wheel.

**Comment by Ksengine** [comment]
@linuxlawson 
Hi, visit @quantumgui and accept my invitation
