### ISSUE TITLE
Mode button seems to lose text when changing options

### ISSUE THREAD

**Issue by jimbob88** [linuxlawson/texpert#3]
![Screenshot from 2019-03-11 17-16-52](https://user-images.githubusercontent.com/9913366/54143316-7cce1180-4421-11e9-9b52-315ea05ff6dd.png)
Tested on Ubuntu 18.04 - seems to not have any errors but there is a blank option available in the setup menu.

**Comment by linuxlawson** [comment]
Its like a default blank, i'm trying to get rid of it, ill figure it out soon enough..

**Comment by linuxlawson** [comment]
Yep that did it. Thanks a lot!

**Comment by linuxlawson** [comment]
fixed!
