### ISSUE TITLE
Ubuntu 18.04 - Window isn't sized correctly

### ISSUE THREAD

**Issue by jimbob88** [linuxlawson/texpert#4]
![Screenshot from 2019-03-11 17-22-24](https://user-images.githubusercontent.com/9913366/54143717-4ba21100-4422-11e9-8adf-2a9c8de4fd96.png)
No errors encountered and is fixed when resizing (perhaps default size needs to be changed)

**Comment by linuxlawson** [comment]
Buttons aren't showing up? I changed this a little. Let me know if its still a problem..

**Comment by linuxlawson** [comment]
If I can remember right, I took the 'height' property out of the note_area > tx=Text line. That fixed it for me. In case you still need to know..

**Comment by jimbob88** [comment]
Cool, mine uses a combination of both grid and pack managers so doesn't require it - thank you though

**Comment by jimbob88** [comment]
Seems like after the [latest commit](https://github.com/linuxlawson/texpert/commit/e0efc2648e7d9d352ffe0a0069d06561a4ae6f08) it still doesn't work properly.
![Screenshot from 2019-03-16 11-05-29](https://user-images.githubusercontent.com/9913366/54474329-6d611680-47db-11e9-84bd-f5702af46d94.png)

**Comment by linuxlawson** [comment]
It seems I closed this issue, and kinda forgot about it (sorry about that).  Do you know if this is still a problem?

**Comment by linuxlawson** [comment]
Nevermind this, I did change the default size. So, should be ok.
