### ISSUE TITLE
According to the code the note window should only be opened once

### ISSUE THREAD

**Issue by jimbob88** [linuxlawson/texpert#5]
According to the code:
```
def note_area():  #if opened, dont open again (fix)
    btn_frame = Frame()
    note = LabelFrame(texpert, bd=1, relief='ridge')
```
It would be inferred that the notes should only be able to be opened once, if not this issue can be closed, otherwise I am receiving this effect when opening the notes area:
![Screenshot from 2019-03-11 18-43-26](https://user-images.githubusercontent.com/9913366/54149223-95442900-442d-11e9-927f-f0e1fce09691.png)

**Comment by linuxlawson** [comment]
Yes I realize this is happening. I'm working in it but having a hard time fixing it. Seems like a simple fix but I cant find any info. I'm also working on the other 2 issues you mentioned. 
Thanks for the reminder. -Dave

**Comment by jimbob88** [comment]
@linuxlawson Okay cool sounds good ( seems like on my build of your code it is fixed ) perhaps try looking at that to get an idea of how to get it working ( just as a quick note if you do you'll need to replace the command `vars(self)` with either `globals()` or `locals()` - Jim

**Comment by linuxlawson** [comment]
Ok thanks, I'll look into it. Can I use what you did with the toolbar to?

**Comment by jimbob88** [comment]
@linuxlawson Feel more than free :grinning:

**Comment by linuxlawson** [comment]
Ok thanks, I don't understand it yet, but ill make it work. I didn't know you could use grid and pack together like that..

**Comment by jimbob88** [comment]
@linuxlawson Yeag, there may be a neater way of doing it but I found the solution I used was good enough for it's job

**Comment by linuxlawson** [comment]
I still cant get the notes window to stop opening more than once. I tried several things including some of your code, cant get it working. I dont really understand how globals work. Any help would be appreciated. -Dave

**Comment by jimbob88** [comment]
# Best way to fix it
I seemed to have fixed the issue with your code - the fully changed code is available [here](https://pastebin.com/EQBPbH6H).

The code changes are as follows:

### Line 354-365
```
btn_frame = Frame()
note = LabelFrame(texpert, bd=1, relief='ridge')

tx = Text(note, width=18, bd=0, relief='flat', padx=2, pady=2)
tx.insert('1.0', "Nothing here is saved..")
#tx.bind("<FocusIn>", lambda args: tx.delete('1.0', 'end')) #optional
tx.config(wrap="word")
tx.pack(side='top', fill=BOTH, expand=True)
a = Button(note, text="Clear", width=4, command=lambda: tx.delete('1.0', 'end-1c'))
a.pack(side='left', anchor=S, padx=2, pady=2)
b = Button(note, text="Close", width=4, command=note.destroy)
b.pack(side='right', anchor=S, padx=2, pady=2)
```
The Notes Area is created at the beginning of the program (rather than being called by a function), without being packed ( this allows it to be packed later)

### Line 282-283
```
is_notearea = tk.BooleanVar()
is_notearea.trace('w', lambda *args: note_area())
toolmenu.add_checkbutton(label="Note Area", variable=is_notearea)
```
This initializes a new _global_ variable of the type BooleanVar. A BooleanVar is either True or False. It acts like any other variable yet uses the `set()` command to change it's value or `get()` to retrieve it's current value. The `trace('w')` runs the following command whenever the variable `is_notearea` is changed. To read more about tkinter vars check [this link](http://effbot.org/tkinterbook/variable.htm)

### Line 306
```
b4 = Button(toolbar, text="Notes", width=4, command=lambda: is_notearea.set(not is_notearea.get()))
```
The command is changed to the `set()` command to change the value of `is_notearea`. The command `not is_notearea.get()` sets `is_notearea` to whatever the current value isn't (so True would change to False and False would change to True).

### Line 144-150
```
def note_area():
    if is_notearea.get():
        note.pack(side='right', fill=Y, padx=0, pady=0)
        btn_frame.pack(side='bottom', fill=Y, padx=0, pady=0)
    else:
        note.pack_forget()
        btn_frame.pack_forget()
```
If `is_notearea` is equal to True pack, else forget the current pack.

# Second way to fix it (slightly simpler)
The alternative fix is to use [this code](https://pastebin.com/4KFQsq2M).

### Line 282-283
```
is_notearea = tk.BooleanVar()
#is_notearea.trace('w', lambda *args: note_area())
toolmenu.add_checkbutton(label="Note Area", command=note_area)
```
Simply runs the `note_area` code on click (checkbutton used for clarity of when note_area is made)

### Line 144-151
```
def note_area():
    is_notearea.set(not is_notearea.get())
    if is_notearea.get():
        note.pack(side='right', fill=Y, padx=0, pady=0)
        btn_frame.pack(side='bottom', fill=Y, padx=0, pady=0)
    else:
        note.pack_forget()
        btn_frame.pack_forget()
```
Simply on the command being ran it flips the current value and does whatever the result.

**Comment by linuxlawson** [comment]
It looks like you put a lot of work into this. Sorry if it was to much trouble. Anyway, both solutions seem to work perfectly. Appreciate all your help. Thanks!

**Comment by jimbob88** [comment]
@linuxlawson Don't worry about it, I'm happy to help - Jim
