### ISSUE TITLE
Select All doesn't work in the latest edition

### ISSUE THREAD

**Issue by jimbob88** [linuxlawson/texpert#6]
## Issue
On `Ctrl+a` being pressed the following error occurs:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1544, in __call__
    return self.func(*args)
TypeError: select_all() takes no arguments (1 given)
```
## Solution
Replace the line `def select_all():` with `def select_all(event=None):`

**Comment by linuxlawson** [comment]
Hey Jim, good to hear from you. I fixed the problem with the solution you presented, all is good. 
Thanks a lot!

I have another question but hate to bother you with it. I'll lay it on you and leave it up to you. I'm trying to replace the checkbox in statusbar with something more useful. Here is what i'm working with:

def linecount(event):
    (line, char) = map(int, event.widget.index("end-1c").split("."))
    print line, char  # prints to terminal, of course

texpert.bind("<KeyRelease>", linecount)

This works like it should but I cant figure how to print the line/character numbers in statusbar (where checkbox is). It seems simple enough.. 

Anyway, dont bother with it if its too much trouble. And thanks again for your help.

**Comment by linuxlawson** [comment]
There should be a KeyRelease in the bind. It got left out because of the quotes I'm guessing. 

-Dave

**Comment by linuxlawson** [comment]
It seems that line/character count is more complicated than I initially thought it would be. I'm going to forget about that for now. Sooner or later though, that blackout feature will be gone, I don't like it and it serves no purpose lol. Thanks again for previous help.

By the way, your code has a wildcard in the ScrolledText import (my mistake, i put it there). I've read its not a good idea to use wildcards, that line could be replaced with 'import ScrolledText as tkst'.
-Dave

**Comment by jimbob88** [comment]
> It seems that line/character count is more complicated than I initially thought it would be. I'm going to forget about that for now. Sooner or later though, that blackout feature will be gone, I don't like it and it serves no purpose lol. Thanks again for previous help.
> 
> By the way, your code has a wildcard in the ScrolledText import (my mistake, i put it there). I've read its not a good idea to use wildcards, that line could be replaced with 'import ScrolledText as tkst'.
> -Dave

I have left that mode on the Python2 section because scrolled text contains purely scrolled text, I personally have no issue with importing Scrolled Text like that. If you look at the way it is imported in Python3:
```python
from tkinter.scrolledtext import ScrolledText
```

It is an item you are importing from the tkinter module so I see it as a good enough solution. Maybe I'll change it in the future but I feel it is okay for the moment

**Comment by jimbob88** [comment]
> Hey Jim, good to hear from you. I fixed the problem with the solution you presented, all is good.
> Thanks a lot!
> 
> I have another question but hate to bother you with it. I'll lay it on you and leave it up to you. I'm trying to replace the checkbox in statusbar with something more useful. Here is what i'm working with:
> 
> def linecount(event):
> (line, char) = map(int, event.widget.index("end-1c").split("."))
> print line, char # prints to terminal, of course
> 
> texpert.bind("", linecount)
> 
> This works like it should but I cant figure how to print the line/character numbers in statusbar (where checkbox is). It seems simple enough..
> 
> Anyway, dont bother with it if its too much trouble. And thanks again for your help.
### The Code
I have a code with the fix [here](https://pastebin.com/ezHgrg4E). 

### Notes

I have given three options for the configuration:

The one that answers the question and is written in the recommended format:
```python
line_lbl['text'] = 'Ln {line}, Char {char}'.format(line=line, char=char)
```
It simply states: set the variable `line_lbl`'s text attribute to 'Ln {the current line}, Char {the current cursor position}'

The more commonly used formatting (works in the same way):
```python
line_lbl.configure(text='Ln {line}, Char {char}'.format(line=line, char=char)) # you may prefer to stick with this statement instead
```

The final option uses a GEDIT like system (one that I'd recommend as it makes quite a lot of sense that might just be me though):
```python
line_lbl['text'] = 'Ln {line}, Col {col}'.format(line=line, col=char+1) # Columnular system over characters (same as GEDIT)
```
And the easiest way to think of the way it works is by building a table:

|   | 1 | 2 | 3 | 4 | 5 |
|---|---|---|---|---|---|
| 1 | H | E | L | L | O |
| 2 |   |   |   |   |   |

So the first character is the first column, the second character is the second position. It just means if you have a white-space it can make more sense.

Hope this helps :+1:

**Comment by linuxlawson** [comment]
I had a heck of a time choosing between the 3 options. In the end I went with the gedit layout.  I also hate having to use 'Ln' instead of 'Line' but I looked at a few other editors and they all do the same. Some kinda tradition I guess. 
Anyway, thanks again for all your help, I appreciate it a lot.

**Comment by linuxlawson** [comment]
Counting the cursors position vs only whats typed before, was also a hard choice.

Thanks again. -Dave

**Comment by jimbob88** [comment]
No Problem, I am always more than happy to help. I spend more than too much time programming with Tkinter/Python :) I just hope my knowledge can help other users
