### ISSUE TITLE
shortcut keys (in menu)

### ISSUE THREAD

**Issue by linuxlawson** [linuxlawson/texpert#7]
Shortcut keys in menu are right-aligned on my system (linux mint). Don't know if that's the case on all systems/distros?
Will leave as is for now.

**Comment by jimbob88** [comment]
On Windows 10 they look like this:
![image](https://user-images.githubusercontent.com/9913366/99841599-594fe980-2b66-11eb-9229-262c1cd94974.png)

By the way, with the latest version I got this error on first run (I use anaconda python 3.8.3):

```
>python texpert.py
  File "texpert.py", line 57
    contents = file.read()
                         ^
TabError: inconsistent use of tabs and spaces in indentation
```

After running `autopep8` on it it worked perfectly:
```
>python -m autopep8 texpert.py --in-place
```

**Comment by linuxlawson** [comment]
This works on windows? Never really thought about that, I'm using Linux.
Anyway, thanks for taking the time to check that out, I'm going to change exit to 'Ctrl+Q' and call it good.

I'm going to leave this open for a couple days and see if anyone else chimes in. And I'll work on the indentation issues.
Thanks again!

**Comment by linuxlawson** [comment]
I'm assuming this will be fine.
