### ISSUE TITLE
cross-platform

### ISSUE THREAD

**Issue by Ksengine** [linuxlawson/texpert#8]
**why this is for linux only?**
please give me a list of reasons?
_I can help to make this cross platform_

**Comment by Ksengine** [comment]
add suitable labels

**Comment by linuxlawson** [comment]
I don't have Windows on my computer so I never really thought about it working correctly on Windows. If it does, that's awesome!
   On Friday, November 20, 2020, 10:08:33 PM EST, Kavindu Santhusa <notifications@github.com> wrote:  
 
 


why this is for linux only?
please give me a list of reasons?
I can help to make this cross platform

**Comment by linuxlawson** [comment]
Whats wrong with my labels? Am I doing something wrong?

**Comment by Ksengine** [comment]
no no
just add labals like `question` `future` `enhancement`

**Comment by Ksengine** [comment]
remove these lines because this imports are not used
- https://github.com/linuxlawson/texpert/blob/e195e6ae86dc2f065db19fe74eeef0e09ac8cb34/texpert.py#L6
- https://github.com/linuxlawson/texpert/blob/e195e6ae86dc2f065db19fe74eeef0e09ac8cb34/texpert.py#L7
- https://github.com/linuxlawson/texpert/blob/e195e6ae86dc2f065db19fe74eeef0e09ac8cb34/texpert.py#L9
- https://github.com/linuxlawson/texpert/blob/e195e6ae86dc2f065db19fe74eeef0e09ac8cb34/infobox.py#L5
- https://github.com/linuxlawson/texpert/blob/e195e6ae86dc2f065db19fe74eeef0e09ac8cb34/infobox.py#L6

other imports are
- tkinter(cross platform)
- time(cross platform)

**so this text editor is cross platform**

**Comment by linuxlawson** [comment]
OK, I took out the imports and nothing broke, so that's good. I had to keep import time because I have 'Insert Time' as a tool in my tool menu. Thanks for the Info!

**Comment by Ksengine** [comment]
> so this text editor is cross platform

?
change your descriptions

**Comment by linuxlawson** [comment]
Done.

**Comment by linuxlawson** [comment]
Doesnt this have to be made executable to work on windows?
and python has to be installed on windows in order for it to work?

That's why I wasn't sure it would work on Windows

**Comment by Ksengine** [comment]
Use pyinstaller or cxfreeze

**Comment by linuxlawson** [comment]
ok
